#!/usr/bin/env zsh
# Description:
#   Self management of zplug

if ! __zplug::base::base::zpluged $_ZPLUG_PACKAGE; then
    __zplug::io::print::f \
        --die \
        --zplug \
        "$_ZPLUG_PACKAGE: not managed yet\n"
    return 1
fi

ln -snf \
    "$ZPLUG_REPOS/$_ZPLUG_PACKAGE/init.zsh" \
    "$ZPLUG_HOME/init.zsh"
